Lxd instance (#56)
* test lxd client

* linting

* cli as param in PyLXDWrapper.run

Dynamically get the service from the client and method from the service

* fixing logic

* fix run params

name and config are not required for all service.method calls

* typo

* Update utils.py

* Moved pylxd Client to cloudcix.rcc

* comms_lxd epects endpoint_url

* Update test_bridge_lxd.py

* cloudcix version greater than 0.15.0 required

* revert changes in bridge kvm

* templates not included in pip install

* package subfolders in templates in pip install

* render templates in bridge kvm via utils

* rename templates folder

* Updated MANIFEST.in

recursive-include all jinja templates in templates path

* Update setup.py

* Update bridge_kvm.py

* rendering jinja templates

nginxns and dchpns render templates via utils.JINJA_ENV

* bridge_lxd build

* bridge_lxd read

* bridge_lxd scrub

* Update bridge_lxd.py

* bridge_lxd scrub

* correct logic eval in scrub

* cloudcix >= 0.15.2

Support rcc.comms_lxd api=True requests

* Create lxd.py

* Update hyperv.py

* lxd build

* remove secondary storages from hyperv build

- Secondary storage drives should be managed by the stroage_hyperv primitive

* lxd userdata and network_config

* typo

* resolve SyntaxError

SyntaxError: positional argument follows keyword argument

* define each kwarg seperately

* typo

* instance_type check

* Update test_lxd.py

* config is a keyname in instances.create

* userdata and network_config not objects

* extend userdata in test

* waiting to start

Test waiting for VM to start before returning True

* do not include version in network_config

* Update lxd.py

* Update test_lxd.py

* Update test_lxd.py

* lxd.quiesce

* lint

* quiesce  verify_lxd_certs

* lxd.restart

* lxd scrub

* lxd read and scrub

* extend comments

* Update lxd.py

---------

Co-authored-by: oscar-lenin <167421279+oscar-lenin@users.noreply.github.com>